### PR TITLE
Fix/all colnames in atc name condition

### LINKED ISSUE #120: [Potential bug]: 🐛 Look into `!all(colnames(data) %in% c("atc", "name"))` condition in `simulate-data.R`
This condition is used in `insert_false_metformin()` and `insert_false_drug_names()`

### PR DESCRIPTION
**Pull request by signekb**
## Description

- This PR flips (and in my opinion simplifies) the condition in `insert_false_metformin()` and `insert_false_drug_names()`.
- It also adds "indo" to the conditon in `insert_false_metformin()` since this column is used to filter within the function. 

About the condition: 
- Before, the condition was True only if **all** colnames in data was "atc" and "name" (we wanted it to be True if both "atc" and "name" are in the column names)
- To fix this, I flipped the condition so it's True when both "atc" and "name" are in colnames. The flip was mostly to avoid the "!" and make the condition more intuitive.  

## Issues 

Closes #120

### CODE REVIEW

File: data-raw/simulate-data.R [hunk 1]
```diff
@@ -152,37 +152,39 @@ insert_specific_atc <- function(data, proportion = 0.3) {
...
+        ),
+        name = dplyr::if_else(
+          indo %in% c("0000092", "0000276", "0000781") & insertion_rate(proportion),
+          "metformin",
+          name
+        )
       )
-    )
+  } else {
+  return(data)
```
Comment (lwjohnst86) [inline data-raw/simulate-data.R:170]:
```suggestion
  data
```

Only minor thing here, since each if else condition outputs a tibble, we don't need to use return here.

File: data-raw/simulate-data.R [hunk 2]
```diff
@@ -152,37 +152,39 @@ insert_specific_atc <- function(data, proportion = 0.3) {
...
+    data |>
+      mutate(
+        name = case_when(
+          atc == "A10BJ06" & insertion_rate(proportion) ~ "Wegovy Flextouch",
+          atc == "A10BJ02" & insertion_rate(proportion) ~ "Saxenda",
+          TRUE ~ name
+        )
+      )
+  } else {
     return(data)
```
Comment (lwjohnst86) [inline data-raw/simulate-data.R:186]:
```suggestion
    data
```

**Review by lwjohnst86 — CHANGES_REQUESTED** [review]
Nice! only minor edits.

File: data-raw/simulate-data.R (hunk 1 above)
Comment (signekb) [reply data-raw/simulate-data.R:170]: Ah, nice!

**Review by Aastedet — APPROVED** [review]
